typography_spectrum: 0.8961574304848909
color:
  brandColors:
    - '#FF6138'
    - '#FFFF9D'
    - '#BEEB9F'
    - '#79BD8F'
    - '#00A388'
  brandStrength: 0.8285980424843729
  lightness: 0.8688939854037017
  saturation: 0.15645587327890098
  rhythmicContrast: 0.003056806745007634
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.9737019103486091
analytics:
  google: null
  facebook: null
  twitter: null
name: Provocateur
cta:
  domain: null
  bucket: null
  version: null
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
