favicon: null
name: Provocateur
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.4999715415760875
  brandStrength: 0
  lightness: 0.4061801191419363
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  rhythmicContrast: 0.5615105698816478
typography_spectrum: 0.1316454012412578
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.9381619584746659
analytics:
  twitter: null
  google: null
  facebook: null
